package com.atenea.android.voiceruntime

data class AteneaVoiceRuntimeState(
    val serviceActive: Boolean = false,
    val captureActive: Boolean = false,
    val audioRoute: String = "unknown",
    val audioRouteLabel: String = "Desconocida",
    val audioOutputStreamVolume: Int = 0,
    val audioOutputStreamMaxVolume: Int = 0,
    val outputGain: Float = 1.0f,
    val sampleRateHz: Int = 24_000,
    val rmsDb: Double? = null,
    val peakLevel: Double = 0.0,
    val wakeWordStatus: String = "not_configured",
    val realtimeStatus: String = "not_connected",
    val realtimeConnected: Boolean = false,
    val realtimeTransport: String? = null,
    val realtimeModel: String? = null,
    val realtimeVoice: String? = null,
    val inputSpeechActive: Boolean = false,
    val outputPlaybackActive: Boolean = false,
    val playbackCompletionCount: Long = 0L,
    val bargeInTriggerCount: Long = 0L,
    val lastUserTranscript: String? = null,
    val lastUserTranscriptSequence: Long = 0L,
    val lastAssistantTranscript: String? = null,
    val bargeInStatus: String = "disabled",
    val lastErrorCode: String? = null,
    val lastErrorRecoverable: Boolean = false,
    val lastEvent: String = "Runtime nativo parado.",
    val updatedAtMillis: Long = System.currentTimeMillis()
)
