package com.atenea.api.mobile;

public enum MobileSessionOperatorState {
    DEFAULT,
    RUNNING,
    CLOSING_REMOTE,
    REMOTE_CLOSE_BLOCKED,
    LEGACY_CLOSE_REQUIRED,
    CLOSED_OWNER_BLOCKS_CAPACITY,
    CLOSED_OWNER_RECONCILING,
    CAPACITY_RELEASED,
    SOURCE_READINESS_PENDING,
    SOURCE_ADVANCED,
    OWNERSHIP_REVIEW_REQUIRED,
    CLOSED
}
