package com.atenea.persistence.core;

public enum CoreTargetType {
    PROJECT,
    WORK_SESSION,
    SESSION_TURN,
    SESSION_DELIVERABLE,
    OPERATOR_CONTEXT,
    PROJECT_VERIFICATION_RUN,
    PROJECT_DATABASE_REFRESH_RUN,
    MANAGED_HOST,
    MANAGED_SERVICE,
    OPERATIONS_INCIDENT,
    OPERATIONS_ACTION_RUN
}
