package com.atenea.persistence.core;

public enum CoreResultType {
    PROJECT_OVERVIEW_LIST,
    PROJECT_OVERVIEW,
    PROJECT_CONTEXT,
    WORK_SESSION_SUMMARY,
    SESSION_DELIVERABLES_VIEW,
    SESSION_DELIVERABLE,
    WORK_SESSION,
    WORK_SESSION_VIEW,
    WORK_SESSION_CONVERSATION_VIEW,
    PROJECT_VERIFICATION_RUN,
    PROJECT_DATABASE_REFRESH_RUN,
    OPERATIONS_HOST_LIST,
    OPERATIONS_HOST_STATUS,
    OPERATIONS_SERVICE_CHECK,
    OPERATIONS_WEBSITE_CHECK,
    OPERATIONS_INCIDENT,
    OPERATIONS_ACTION_RUN
}
