package com.atenea.persistence.core;

public enum CoreResultType {
    PROJECT_OVERVIEW_LIST,
    PROJECT_OVERVIEW,
    PROJECT_CONTEXT,
    WORK_SESSION_SUMMARY,
    SESSION_DELIVERABLES_VIEW,
    SESSION_DELIVERABLE,
    WORK_SESSION,
    WORK_SESSION_VIEW,
    WORK_SESSION_CONVERSATION_VIEW
}
